### ISSUE TITLE
Include validation and report output in tls test.

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#107]

**Comment by ewRedstone** [comment]
https://github.com/grafnu/daq/pull/101

Tested end to end with real devices and faux devices. Also tested with Travis CI

**Comment by grafnu** [comment]
I have no idea what this issue is about, so assigning back to Francesco.

**Comment by ewRedstone** [comment]
@grafnu @pisuke This is essentially the project plan of tests Redstone are developing. Some tests have pull requests associated with them. As I believe as soon as a PR is merged with grafnu/master I assume the issue here can be closed. Or are issues only able to be closed when the grafnu/master has been merged with faucetsdn/daq ? just a questions surrounding process and closing out issues

**Comment by grafnu** [comment]
Issues can be considered closed when they are pulled into grafnu. The "push
to faucetsdn" part is just administrative (I just push from one to the
other).  The reason for this is just administrative rights, nothing
semantic. For when a "test is completed" question, then it literally comes
down to looking at the device_report.md report summary table of grafnu
<https://github.com/grafnu/daq/blob/master/docs/device_report.md#report-summary>,
since this is an active reflection of the code that is submitted and
running.  (The tests don't need to *pass* there, just be listed.)
