### ISSUE TITLE
Include validation to ntp.support

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#113]

**Comment by aidanparkinson** [comment]
Test renamed `network.ntp.update` in file `Redstone DAQ Device Qualification Test Tracker Triage`

**Comment by ewRedstone** [comment]
addressed in https://github.com/grafnu/daq/pull/119

**Comment by ewRedstone** [comment]
grafnu 12 days ago  Owner
I don't understand what this is doing. You won't see ntp or any other unicast traffic in this test container (since it's sent only to the destination) -- I'm confused as to what this test is doing.

  @ewRedstone
ewRedstone 11 days ago  Author Collaborator
This code is for use with the other Docker build file added to this PR. Using the code this way with multiple docker containers allows separate tests to pass as a line item in DAQ feedback page
https://curious-song-211910.firebaseapp.com/?origin=daq-testing-account

  @grafnu
grafnu 11 days ago  Owner
That didn't answer my question. You can't/shouldn't be capturing traffic not intended for this container within this container, since you likely will never see it. NTP is going to unicast to the NTP server, not this container. And even things like arp aren't guaranteed to make it here if the networking system decides they don't need to (ARP is a very low-level networking operation).

This is why the scans/ folder exists, since they are drawn from content that's outside of the container.
