### ISSUE TITLE
Tutorials shouldn't require sudo

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/daq#117]
Commands (cmd/build) shouldn't require sudo to run (e.g. in the tutorial). If there are problems that require it then they should be identified and fixed.

**Comment by pisuke** [comment]
@grafnu I've tested again from a fresh start and sudo is not required for most of the steps except for cmd/build, since it needs docker to run. Docker needs admin rights in normal configurations, unless [these steps](https://docs.docker.com/install/linux/linux-postinstall/) are taken. 
Should we add these steps in the wiki and assume docker can be run as user?

**Comment by grafnu** [comment]
Yes, we should enable that. I think we can automate some of it (put it in the setup script) to help out. I think the one tricky bit is it requires a system restart... but that's easy enough to advise.

**Comment by InBrewJ** [comment]
Closed by https://github.com/arupiot/daq/pull/4
