### ISSUE TITLE
Add capability to access auxiliary device configuration files from test docker container to be available at run time test

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#140]
Some tests will need to access auxiliary files stored in the local/site/mac_addrs/##:##:##:##:##:##:##:## folder.
Can DAQ volume map this folder so that the test docker container can access them?

**Comment by grafnu** [comment]
Is there an example of what some of these files?  I'm trying to put some controls on what "bleeds" out/in to tests, because it causes management headaches down the line. If the information is simple enough, then it should go in the module_configs.json file (e.g. like port-open mappings).  If there's a sample or two of the expected values then we can sort through the right answer.  Once the door is open to a "generic file dump" then typically people will abuse it.

**Comment by pisuke** [comment]
Sure, here is an example of a csv file (zipped because GitHub wants it) for the BACnet PIC statement test.
[DAQ_PICS - PIC_template.csv.zip](https://github.com/faucetsdn/daq/files/3271268/DAQ_PICS.-.PIC_template.csv.zip)
This file is created from a [spreadsheet](https://docs.google.com/spreadsheets/d/1llJkb9NZ-JidnCHuQRn95A1OoPvvjpPGYo95-5Pe4QY/edit?ts=5ce3f3c1#gid=0).
It is intended to be created by the operator matching the PIC statement so that it can be parsed by the test code (PIC statements are provided as PDF files unfortunately).

**Comment by grafnu** [comment]
Is that set of information going to be unique to the site-install, a device type, or specific device?

**Comment by ewRedstone** [comment]
Hi Trevor,

The information is unique to specific device.

However some manufacturers like EasyIO have a standard PIC Statement that all there products comply with.

Hope this helps.

Im wondering if all it requires is a tmp/pic_statements folder as I think it would be good to be able to use pic statements that have already been converted to the csv format over and over again.

Pic statements rarely change so this information is kind of static rather than in continuous flux.

Hope this clarifys reasoning

**Comment by grafnu** [comment]
How does it differ between specific devices? A specific example would be most useful.  I'm trying to understand the level of granularity that would be most effective. 

The "all it requires" answer is not always the right one -- it can often end up being the "easy way out" which just leads to mess later on. I want to understand the underlying need first before jumping in to just the easy solution.

The other bit of information that comes up that's relevant I think are things like a device key that are used for Cloud IoT communication -- so trying to figure out the one right solution for both.

**Comment by jcbrough** [comment]
I'm not sure that PIC Statements are always a good basis for this, unless we are only considering applying this to BACnet compliant products - which I doubt.

Many controls manufacturers, have BACnet implementations which only expose a very thin veneer of objects and services to the protocol. Where these products are used many of the functions that will be required for a useful IoT device (e.g. access to Trend Log data, Time Schedules, PID Loop parameters) are only available via its proprietary protocols (e.g. TCOM / SOX) - these will need testing as well and they are not defined in BACnet PIC Statements but elsewhere in the specific product documentation.

True native BACnet devices will be fine with definition by PIC Statement as this is the 'operating system' that the device is built on and so it captures everything, but products that have internal gateways that map internal proprietary protocols to a thin emulated BACnet veneer are not suitable for defining this way, as if we only consider BACnet services then it will leave all of the proprietary services untested and unqualified.

**Comment by grafnu** [comment]
Thanks for the thoughts. The question here wasn't really about "BACnet PIC"
-- that was just a singular concrete example -- but rather what DAQ
framework improvements are necessary to support this sort of test. The
salient question here is "what information should be exposed to a test to
validate device behavior" -- e.g. for a simple network portscan, knowing
that "Port 443 should be open" and "Port 23 should not be open" are
important because then if port 23 is open it fails, or if port 443 is
*not* open
then it would be a warning.  The issue of what actually needs to be tested
for a particular class of device then falls down to the tests themselves.
What I'm trying to understand if simply mapping a device-specific volume
table is the most appropriate fix. I'm thinking there will be utility in it
-- even for things like Cloud IoT authentication keys.

**Comment by jcbrough** [comment]
Yes agreed. I was a bit worried that too broad a brush was being suggested by assuming that a PIC statement was an easy catch all. With EasyIO and others it plainly is not as there will be other ports that need to be open for the proprietary protocols to work and these need to be factored in.

I guess what we are searching for is some machine readable format to define what is permissible so that when DAQ runs it knows what should be open and can verify that?

**Comment by pisuke** [comment]
Sorry for the late reply on this.

So, the PIC statement is unique for a specific DEVICE TYPE, and the test is to match that the device reports the same capabilities of the PIC statement.

But focusing on the reason for this issue/feature request, I think there is a lot of value in providing the possibility to access a device specific volume from inside a test docker container.
It allows the test developer to create code supporting workflows where something specific about the device or device type can be described (the authentication keys example is great).

**Comment by jcbrough** [comment]
You could do this if you wanted to go so deep into verifying the BACnet objects, properties and services of each device. What I'm not sure of is whether you want to, this work has already been done by an independent verification test house - so long as you only use BTL Listed products.

For reference: the Device Object in BACnet defines the properties that contain this information and you could verify them against a JSON or other format file created from the PIC Statement for each device type.

Attached is an example of some of the properties of the DEV object of a Delta Controller read from our BACnet-AWS.

The PIC Statement for all BTL Listed products are available on the BACnet International website, e.g. 
[https://www.bacnetinternational.net/catalog/manu/delta%20controls/pics_for_entelibus_4.1.pdf](url)

This will however only test the BACnet Protocol. Devices that have other protocols (e.g. TCOM / SOX / etc.) may have other vulnerabilities and the implications of those protocols should also be considered.
![eBCON DEV Object](https://user-images.githubusercontent.com/41573774/59268972-c9560280-8c45-11e9-93c7-3758d82ba165.JPG)

**Comment by pisuke** [comment]
Interesting how this thread started with a request to add a volume mapping functionality and has developed into a discussion about BACnet ;-)

Thanks for the comments.
Getting the devices tested once by an independent institution is OK, but I understand that one of the aim of DAQ is to implement continuous testing. In this context, even PIC statement can be checked against a firmware upgrade for instance, or a device fault.

If we'd like to discuss more specifically about PIC statements, I suggest we move the conversation on the relevant issue #130.

Let's talk here only about the feature request. 
As I said, there is a lot of value in providing the possibility to access a device specific volume from inside a test docker container.
It allows the test developer to create code supporting workflows where something specific about the device or device type can be described (the authentication keys example provided by Trevor is great, the PIC statement check is another).

**Comment by grafnu** [comment]
Currently being addressed in https://github.com/grafnu/daq/pull/152

**Comment by grafnu** [comment]
This has been done!

**Comment by pisuke** [comment]
Thank you Trevor!
