### ISSUE TITLE
poe.support generates invalid "fail" result

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#204]
Unable to generate a test result that returns poe.negotiation = "pass" and poe.support = "fail". I don't see any reason why this should be the case, perhaps a bug?

**Comment by pisuke** [comment]
If poe.support fails poe.negotiation should also fail. I'll check out the behaviour and report.

**Comment by pisuke** [comment]
@jhughesbiot please note that the PoE tests output for non PoE devices is not correct. See the report below for reference.

[device_report_non_poe_device.pdf](https://github.com/faucetsdn/daq/files/4649687/device_report_non_poe_device.pdf)

The report output for a non-PoE device should be `skip` in all cases with a sensible summary output stating something like `Test skipped because the device does not support Power over Ethernet` or something similar.

Can you please address this bug?

@spectre-storm for information.

**Comment by jhughesbiot** [comment]
Did you disable PoE in the devices module_config.json?  If PoE isn't disabled at the device level, it is going to attempt to test as a PoE device.

**Comment by jhughesbiot** [comment]
A quick comparison of switch output of PoE and non-PoE information.  Port 1 is non-PoE and port 2 is a PoE device.

```
Interface	Admin	Oper	Power	Device	 Class	Max
Gi1/0/1		auto	off	0.0	n/a    	 n/a     30.0
Gi1/02		auto	on	4.0	Ieee PD	 1       30.0
```

You can see they both report auto-negotiation because that's more of the switch configuration setting of the port.  PoE operational determines if PoE is actually in use.

So if PoE is enabled in the device module_config.json, the results for these devices map to

Port 1:
admin:auto -> pass poe.autonegotiation
oper:off -> fail poe.support
oper:off -> fail poe.power

Port 2:
admin:auto -> pass poe.autonegotation
oper:on-> pass poe.support
oper:on and maxPower>=currentPower -> pass poe.power

Without knowing if the device is supposed to support PoE, the switch just reports what it's doing and if a device being told to support PoE but doesn't will come up with failures because the switch reports bad states for PoE.  If a device actually supported PoE but had issues, the switch would report the same failure states so there would be no way to know the difference and skip a non-PoE device based on switch information alone.

**Comment by grafnu** [comment]
Should be a simple truth table, no?  At least I think this is what Jonathan
is saying.  And I think the explicit model is good/better -- we don't need
to get into the "automatically try to determine if the device supports PoE
or not" game.

Enabled == device module_config enabled to say "this device should support
PoE"
Tested == device PoE tests indicates pass/fail

enabled tested result
  N       n/a   skip
  Y      good   pass
  Y      bad    fail

**Comment by jhughesbiot** [comment]
That is essentially how it works now.   No attempt to auto-detect PoE support for the device, just report the state of the tests if enabled and skip if disabled.

If we need to modify the truth table or tweak the results, there's no issue on my end doing that, just need to agree on what those states look like.

**Comment by spectre-storm** [comment]
Francesco to update

**Comment by pisuke** [comment]
I've written this document to explain the issues https://docs.google.com/document/d/1g5BtxFGo53d3b9OOIIbf7AApyEYlWFk0qfA_ezSJWwk/edit# 
PTAL, thanks!
