### ISSUE TITLE
Device configuration for functional testing of security.ports.nmap

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#206]
To understand whether `security.ports.nmap` returns valid integration test results using faux devices, I believe we need to configure all the faux devices with a set of similar "allowed" ports. Does this require a change to daq/misc/test_site/device_types/rocket/module_config.json? Or, might changes be made elsewhere?

**Comment by grafnu** [comment]
Faux devices are not configured through module_config.json, since that
applies to the tests that are running, not the target.  Basically, if it's
some property of the "device" that would normally (with a physical device)
be configured independently of DAQ, then the faux version is configured
elsewhere.

Specifically look in testing/test_base.sh (the integration test script):

# Check that an open port causes the appropriate failure.

cmd/run -s startup_faux_opts=telnet

And then in misc/start_faux (part of the faux device code):

# Setup dummy telnet listener to trigger port-scan failure
if [ -n "${options[telnet]}" ]; then
    echo Enabling mock telnet server...
    (while true; do echo Telnet `hostname`; nc -nvlt -p 23 -e `which
hostname`; done) &
fi

**Comment by aidanparkinson** [comment]
Thanks Trevor, I can see where this has all been done now. This helps me a great deal in understanding the functional tests.
