### ISSUE TITLE
Functional review of security.admin.password

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#242]

**Comment by noursaidi** [comment]
The test workflow appears to require each device (or at least according to the first six characters of the MAC address) to be assigned a set of credentials in the defaultPasswords.json file before the test runs. This also requires a rebuild of DAQ. This is not scalable and usable for unattended installations and processes like remediation. I’d expect the workflow to be automatic and not require any user interventions. In addition, the “default passwords” list is limited, please use a well maintained CSV file from a reputable source that includes manufacturer default credentials to be used. For instance :
- https://gitlab.com/kalilinux/packages/seclists/-/blob/094459e5d757faccfcb44375a2e4c9602d5984d4/Passwords/Default-Credentials/default-passwords.csv
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/Default-Credentials/default-passwords.csv

In all the test description fields the test is described as “Verify all default passwords are updated and new Google provided passwords are set.” The description must change to a relevant one to each test (mentioning the protocol) and not include Google. I suggest something like this: “Check with a brute force password attack that the device passwords for the XYZ protocol are not matching default passwords.” Consequently also a more exact report comment is needed, e.g. “No match in default password dictionary” rather than "passwords have been changed from manufacturer default" when a device passes.

It is also recommended to include the descriptions of the tests in a separate module_manifest.json file for clarity, like in this example: https://github.com/faucetsdn/daq/blob/master/subset/switches/module_manifest.json. 
In addition, the test needs a README.MD file (e.g. https://github.com/faucetsdn/daq/blob/master/subset/pentests/readme.md) which details the pass/fail criteria

I encountered two issues in my testing. Firstly the tests reported a pass for a device with “default credentials” where the device stops accepting requests from DAQ (anti-bruteforce mechanism setup a firewall rule due to 10's failed login attempts in a few seconds). This needs additional consideration, and the test I think should report "gone" or "merr"

Secondly, the HTTP/HTTPS only check against Basic HTTP authentication provided by the webserver. It doesn’t offer any test against authentication provided by the app itself, e.g. through a login form. Where the device was running a web server hosting a simple app with a login form as the homepage with default admin/admin as credentials, the device passed this test.

**Comment by pisuke** [comment]
@em-redstone can you please comment on the report above? There are a few problems that need addressing urgently.

**Comment by em-redstone** [comment]
Hi @noursaidi,

Thank you very much for your input. I would be happy to address the issues you have noted.

**_"The test workflow appears to require each device (or at least according to the first six characters of the MAC address) to be assigned a set of credentials in the defaultPasswords.json file before the test runs. This also requires a rebuild of DAQ."_**

So far I have only tested the passwords module using the faux device feature of DAQ, and not on physical devices yet. Thank you for bringing this issue to mind. 

Would you be able to briefly describe the process you use for running the password module on a physical device so I may be able to adjust the code accordingly?

**_"In addition, the “default passwords” list is limited, please use a well maintained CSV file from a reputable source that includes manufacturer default credentials to be used."_**

Sure, I will update the module to retrieve the default passwords file from a more appropriate source.

**_"In all the test description fields the test is described as “Verify all default passwords are updated and new Google provided passwords are set.” The description must change to a relevant one to each test (mentioning the protocol) and not include Google."_**

**_"Consequently also a more exact report comment is needed, e.g. “No match in default password dictionary” rather than "passwords have been changed from manufacturer default" when a device passes."_**

Will update the test description as suggested.

**_"It is also recommended to include the descriptions of the tests in a separate module_manifest.json file for clarity, like in this example: https://github.com/faucetsdn/daq/blob/master/subset/switches/module_manifest.json.
In addition, the test needs a README.MD file (e.g. https://github.com/faucetsdn/daq/blob/master/subset/pentests/readme.md) which details the pass/fail criteria"_**

Will include documentation: readme.md and module_manifest.json as suggested.

**_"Firstly the tests reported a pass for a device with “default credentials” where the device stops accepting requests from DAQ (anti-bruteforce mechanism setup a firewall rule due to 10's failed login attempts in a few seconds). This needs additional consideration, and the test I think should report "gone" or "merr""_**

Thanks for bringing this up, since the module had only been tested on the faux device feature, I didn't run into this. I will address this in the next push. I could probably make this a skip-case with separate message "Skipped due to anti-bruteforce mechanism"?

**_Secondly, the HTTP/HTTPS only check against Basic HTTP authentication provided by the webserver. It doesn’t offer any test against authentication provided by the app itself, e.g. through a login form. Where the device was running a web server hosting a simple app with a login form as the homepage with default admin/admin as credentials, the device passed this test._**

Thanks for bringing this up, will address this also with a more comprehensive HTTP/HTTPS check as suggested.

Kind regards.

**Comment by noursaidi** [comment]
Hi @em-redstone ,

To test against against a physical device I followed the guidance in the Wiki "Getting Started" page. To configure the password test to run I had to add the first six characters of the MAC address (ie 76-70-FD-A2-F6-DE becomes 7670FD) into the the defaultPasswords.json in src/main/resources , the syntax should be self explanatory as there are examples already there.

I think the overall aim is that this step should be automatic and deduces the manufacturer based on the MAC address. There was some discussion on #377 on using the the MAC addresses prefix downloaded from svnmap through DAQ automatically, maybe that is relevant.

**Comment by em-redstone** [comment]
Hi @pisuke, @noursaidi,

I have pushed the recent changes to my git repo:
https://github.com/em-redstone/daq/tree/security_password

Push changelog:
- Added automated manufacturer password deduction using macoui.
	- Added a splicer script which creates a brute force dictionary using
	macList from nmap, and a .csv file containing passwords from one of the
        sources @noursaidi suggested.
        - Should run automatically to create that dictionary when the docker image is built.
	- Updated the included brute force dictionary using the script. Should now hopefully support 145 unique device manufacturers and about 2800 unique mac ouis.
- Removed google mentions from the test logs.
- Added suggested changes to test reports and outputs.
- Added readme.md file and amended module_manifest.json

In progress:
- Handle bug regarding http login forms
- Handle bug regarding anti-brute force mechanisms
- Considering porting code to bash/python as all it does is read from json and run ncrack/nmap/hydra commands.

Please take a look and let me know if you would like amendments. 

Regards

**Comment by em-redstone** [comment]
Hi @noursaidi, @pisuke,

Hope you are all well, I'm currently working on the suggestions made, but have some queries regarding the test and its requirements.

- Is the requirements of the test to make sure that just default passwords have been changed from manufacturer defaults? Or that passwords have been changed in general to a stronger one?
    - Currently in the test, macoui is used to determine which set of passwords to check against per manufacturer. In the case that the password test generally checks for a strong password, there wouldn't really be a need to use the macoui.
    - The test uses hydra and ncrack to brute force, and it is possible to pass single files containing username/password credentials into the command.
    - In this case, I am considering just collating manufacturer issued username/passwords and common high risk username/passwords into a single large list to use as the brute force dictionary.

- With regards to handling http login forms, I have noticed that hydra/ncrack is able to also brute force login forms, but requires the user to know the 'bad login' response by the webpage when the credentials don't match. However, not all web login forms work in the same way, or have the same 'bad login' response. 
    - In this case, it may be difficult to fully automate. I could probably make a list of bad responses collected from multiple web forms, and run hydra on each one, or the user could put it in manually which might be tedious.    
    - Using a list of bad login responses would probably be possible, but may be limited only to web forms whose bad login messages are in the list. For others I could probably introduce a skip case.

- I've also noticed the password test was also originally written in Java so I have written the rest of the code in the same way, but I have my thoughts that since the code just runs nmap, hydra and ncrack commands, it could probably be simplified to a single script in python or bash, and would reduce Dockerfile build times significantly (since java gradle build takes the longest for this test)

Would appreciate your thoughts and suggestions for these,

Many thanks.

**Comment by em-redstone** [comment]
Hi @pisuke @noursaidi and all, quick update on the test:

Changelog:
- Ported the code from Java to Bash. There are now 2 bash scripts, one which is the password test and the other which creates a single brute force dictionary as opposed to the .json file created previously.
    - This should make it easier to go over or make changes to the code
    - No longer a need for gradle builds which take up a lot of time during build.
- No longer uses ncrack as hydra is able to handle all protocols
- Report messages changed as suggested in the meeting.

I am currently working on the suggested changes:

Single brute force dictionary:
- Based on advice from the meeting, I am ready to remove the previous python script which generates a .json file that needed the macoui for the password test, and replace it with the bash script (also done). The bash script would create a single brute force dictionary independent of macoui. Though the new dictionary made is quite big ~700 credential pairs and may take a while to run. I'll probably take a look at how long it will run tonight with this new dictionary.

Passes on http login forms when it should not:
- I was initially planning on adding web form brute force functionality as it turns out hydra is able to brute force web forms, but the user needs to provide login form element names and the bad login response. This would be something that can't be fully automated, so for now the test will just produce a 'skip' message if it comes across a web form.

Passes when brute force unsuccessful due to firewall when it should not:
- Will probably just look for the messages hydra produces when there is no response from the target, or tcpdump to check for response traffic.

Would appreciate any thoughts and suggestions on these.

Regards.

**Comment by noursaidi** [comment]
Thanks @em-redstone 

With regards to the HTTP web pages, I agree it's not possible to fully automate this for all scenarios, but I think it is important to and think that it should be possible to cover most with an automated method. One approach could be as you have suggested to include common negative responses. Is it possible to instead to use Hydra to look for successful logins? I imagine in most instances the page that follows a successful login is a very different page which doesn't include a login form and usually either an administration console of some sort or "login success" splash page. 

Alternatively, could you use a programmatic method to resolve it by first try a random username & password combination as the first attempt knowing that it wont work which will then give you an example of a "login failed" page to compare subsequent attempts from the dictionary against?

To find the login form, does it not have an option which will automatically pick out a form with a password field? Perhaps there could be a small function which looks through the page.

I'm not exactly sure how web browsers do it wit their saved password feature, but that seems to get it right most of the time to find a page and detect when you've logged in to throw up the "do you want to remember this password prompt"

@pisuke @em-redstone is 700 unique passwords too many? I haven't used many devices with HTTP configuration pages, so I'm not sure the answer, but in your experiences have you come across devices which will support this many login attempts? Perhaps it could start this way and then if there is an issue with tests skipping a finer password list can be used. @pisuke do you think this approach would work?

**Comment by em-redstone** [comment]
Hi @noursaidi,

Thanks for the advice, 

I will have a look at writing a script to find the login forms in the page - I'll read up on some autofill/save password code and see. Hydra currently relies on the selector for the login form and response to be put in manually so this would be very useful.

I do think the dictionary is a bit large and the brute force will take a _really_ long time - the unique user/pass pairs have been collated from the manufacturer.csv file. I've noticed some of the passwords aren't really high risk ones, and would probably benefit from a smaller list, I'll take a look at other files I could run the script on: https://gitlab.com/kalilinux/packages/seclists/-/tree/094459e5d757faccfcb44375a2e4c9602d5984d4/Passwords/Default-Credentials

Regards

**Comment by pisuke** [comment]
@em-redstone do you have an update on this test and some new code we can try out and comment on?

**Comment by em-redstone** [comment]
Hi @pisuke @noursaidi and all, quick update on the test:

**tl:dr:**
- Got hydra command working on DVWA login form, but difficulty getting variations of it to work on other forms. 
- Hydra command is too finicky on syntax, which can result in weird behaviour. Too much variability on web forms to be able to automate this. Can't find other alternative tools.
- I have some experimental code written to retrieve fields from the webpage (excluding cookies and other parameters) but the command they create can't be guaranteed to work.

**Long version:**
I had been trying to get a working hydra command on a sample login form - I managed to find a working hydra command for the DVWA hackable login form: https://github.com/ethicalhack3r/DVWA. It may be that trying to automate web form brute force will be very difficult because of hydra's finicky syntax, and the large variablility of web forms.

The brute forcing process followed was (there are numerous sources online to guide in this):
1. Startup DVWA apache web server.
2. Use something like burpsuite or firefox network monitor to capture HTTP POST packets to retrieve the info needed for the hydra command:
  - request_url (includes the path to the login form, the username/password field names)
  - cookies (in the case of DVWA, php session id and security level)
3. Figure out the success/fail message (hydra provides support for both), and also whether to use http-get or http-post as method.
4. Type up the hydra command and run.

Here is the working command for the DVWA form:
**hydra <host_ip> -V -L <username_file> -P <password_file> <http-get-form/http-post-form> "<path_to_login_form/script>:<username_field_name>=^USER^&<password_field_name>=^PASS^&<login_field_name>=Login:S=<Success_message>:<Cookies dictionary>"**

**e.g. hydra 127.0.0.1 -V -L user.txt -P pass.txt http-get-form "/vulnerabilities/brute:username=^USER^&password=^PASS^&Login=Login:S=Welcome:H=Cookie: PHPSESSID=8e2m61dcuvvn81rs98l6u0ijtb; security=low"**

Complications:
1. Hydra has a finicky syntax and getting the syntax wrong in the slightest way can result in strange behaviour for example: 
- Syntax errors on the cookie field can result in very long brute force times.
- Getting the http method/success/fail messages incorrect can result in all or no passwords in the dictionary to be considered valid credentials. 
2. There is too much variability between web forms, e.g. the DVWA one required a PHP session ID to be present in a cookie, and there was also a user-token field somewhere in the request header. Finding out these extra cookie/token values without having access to a browser will be difficult, and this alone can't guarantee the hydra command will work, again due to the syntaxing which requires some trial and error. I also don't think there's enough transparency on how hydra works internally to be able to make automating it easier.
3. It is difficult to retrieve the request url without pressing the submit button manually on the browser first to get some info from the post request.
4. Also I haven't yet found another alternative to hydra that is able to automatically brute force web forms other than Hatch (which opens up a chrome browser for the user to brute force manually)

So far I have written some code which will retrieve basic fields from the html page, such as username/password field names, method attribute, action attribute and submit field name but again the hydra command created from these will not be guaranteed to work.

Would appreciate your thoughts on this,

Many thanks!

**Comment by grafnu** [comment]
Re: travis -- if you're having specific issues there can you please
separate them out into a separate thread. I don't want to engage in a
discussion across multiple topics in one email thread.

**Comment by em-redstone** [comment]
Thanks Trevor, will move the travis issue to another thread.

**Comment by noursaidi** [comment]
Thanks for the updates @em-redstone , I'll take a look and test some of the changes you have made and report back

**Comment by noursaidi** [comment]
@em-redstone , I've taken a look at the test and tested it under various configurations. I have a few comments:

1. If the HTTP server did not have basic authentication, the test would always fail and report the first username/password combination as the password. This happened even if the server did not have a web form, and when it did it didn't appear to attempt to use the form. Are there any additional instructions to set this up or is the function not included in this PR?
2. When there is a succesful login, the test stops. It should continue to check all the usernames/passwords in the password file and report these (I think because of the -F flag in Hydra)
3. There still appear to be some duplicates in the passwords file.
4. When the server starts to drop connections (e.g. fail2ban or equivalent or network issues), the test goes on indefinitely and timesout.

**Comment by em-redstone** [comment]
Thanks @noursaidi,

_"When there is a succesful login, the test stops. It should continue to check all the usernames/passwords in the password file and report these (I think because of the -F flag in Hydra)"_

Yes, the -F flag stops the brute force once it's found a valid match. I added it in to speed up the runtime as I thought once the user/pass pair is found there won't be a need to continue the brute force for any more credentials - will remove this in next commit.


"There still appear to be some duplicates in the passwords file."

I found about 2 or 3 duplicates, for some reason the script doesn't remove them. It could be due to extra whitespace - I'll try remove this in next commit.

**Comment by em-redstone** [comment]
_"If the HTTP server did not have basic authentication, the test would always fail and report the first username/password combination as the password."_  

Thanks for letting me know about this one, I'll try add some kind of check to prevent this from happening.

_"This happened even if the server did not have a web form, and when it did it didn't appear to attempt to use the form. Are there any additional instructions to set this up or is the function not included in this PR?"_

Also please note the web form brute force isn't in this PR as I've been having trouble getting hydra to work on other webpages other than the DVWA one. Is it possible if you could tell me which devices you are using and the sort of webpages that they use to authenticate? I can then write something to try to get hydra working on those pages. 

At the moment, hydra seems to be the only tool I can find which does brute force on web forms, there are other tools such as hatch but they have guis which make them hard to automate.

**Comment by noursaidi** [comment]
Thanks @em-redstone , I thought it might not have been included. For the web form, I put together my own basic login page for test purposes.

@pisuke, given the difficulties and that it might not detect app based login forms in all instances, should it become a manual test for the cases where there is a app based login form?

**Comment by em-redstone** [comment]
Hi @noursaidi @pisuke and all, quick update:

**_"If the HTTP server did not have basic authentication, the test would always fail and report the first username/password combination as the password."_**

Added check for HTTP authentication now, tested on a docker container with no http authentication configured. It just looks for a '403 Authorization Required' message. Will return a skip case if it runs into this.

**_"When there is a succesful login, the test stops. It should continue to check all the usernames/passwords in the password file and report these (I think because of the -F flag in Hydra)"_**

Test no longer stops once a valid match is found and just continues until the dictionary is exhausted.

**_"There still appear to be some duplicates in the passwords file."_**

Dictionary script now removes duplicates from the colon separated dictionary file. Since ncrack is now being used again, it needs a separate username and password list made from the main dictionary, so duplicates are kept in those files as ncrack goes through them line by line/in pairs.

**_"When the server starts to drop connections (e.g. fail2ban or equivalent or network issues), the test goes on indefinitely and timesout."_**

Switched back to ncrack for http/https/telnet, and now uses medusa for ssh as they have some sort of disconnection handling. Hydra seems to continue when disconnected. I've tested the script in docker by stopping containers midway during brute force and it seems to stop and return a skip result now. I haven't tested it on fail2ban yet as I can't seem to get it working on docker, but I assume the script will behave similarly to a disconnect.

**There were a few reasons why I switched back to ncrack and added medusa:**
- ncrack/medusa have disconnect handling. hydra seems to continue when faced with disconnect.
- medusa runs check on ssh before starting if authentication is allowed.
- ncrack does not have false positives when brute forcing http without authentication.
- hydra previously was having flakyness on telnet and would sometimes hang, ncrack does not do this with the right settings (-T2 aggresiveness setting).

As for runtimes on the full dictionary, ncrack would take 1 minute to run on http(s), 30 minutes on telnet, and medusa 40 minutes on ssh.

Latest changes are in my repo, please let me know how it goes. 

Regards.

**Comment by noursaidi** [comment]
PR #461 merged addressing issues identified in this issue
