### ISSUE TITLE
Develop the security.tls.v1 test (test#47)

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#247]
The following tests must be carried for validation.
1. Minimum version is V1 (this means TLS 1.0) - ERROR if not
2. RSA public key length is 2048 bit minimum - ERROR if not
3. Check if the cipher suite name includes both ECDH and ECDSA with minimum bit length of 224 - WARNING if not.

**Comment by pisuke** [comment]
@jhughesbiot can you please pick up developing this test? I've put a starting point for the test development and validation. Thanks!

**Comment by jhughesbiot** [comment]
There seems to be some recent updates that have severely caused issues with working with this test.  test_aux.sh runs against 3 aux devices, only two generate reports and there is no output of the security module in any of the run nodes to compare what the actual vs expected results are.  Whatever update broke this ability will likely need to be corrected before I can continue troubleshooting this issue.

**Comment by jhughesbiot** [comment]
Pulled the most recent code updates and built and reran test_aux.sh.  None of the 3 aux devices seem to be configured to even run the security module anymore so they won't test existing tls tests and aux device one 9a02571e8f01 always completely fails and stops all tests after its ping failure.

INFO:runner:Target port 1 finalize: ['01:ping:Exception'] (Test initialization failure)
INFO:runner:Target port 1 cancel 9a:02:57:1e:8f:01 (#3/0).

There needs to be a rollback somewhere that broke the CI.

**Comment by grafnu** [comment]
Can you point at the specific spot in a Travis test run where you're seeing
the bad behavior?  I looked at the faucetsdn/daq master runs
<https://travis-ci.com/github/faucetsdn/daq/branches> and they seem ok
(except for the flaky security.passwords.telnet test itself).   I think you
may be misinterpreting some of the log output, but I can't tell for sure
because I don't know exactly what you're looking out. Yes, there is a
"ping:Exception" error in there somewhere, but that's testing the ping
exception specifically -- and there's another test run that tests other
things.  From what I can tell things are working fine, so I'd need more
specific information about exactly what you think is broken (e.g. point me
at a Travis run that has the logs).

If Travis is behaving and it's a local problem then that's something else
entirely, but that doesn't seem to be what you're describing.

**Comment by jhughesbiot** [comment]
I cloned the current code, built and ran the text_aux.sh.  No TLS test is run for any of the nodes. I am not pushing via any PR to travis because I want to verify the test are actually working but am unable to verify the code as is.  Not really sure how else to verify code before creating PR's if local testing isn't supported.

**Comment by jhughesbiot** [comment]
I think i figured out why it's currently impossible to check the results of all the devices under tests in the current code.  There are 6 devices in the test site and only 3 ports available for DUT's.  As soon 1 of the first 3 are completed, those ports get freed up to run the next 3.  So if you attempt to review the results of one of those first 3 that actually ran the TLS tests, as well as other modules not in the second 3, all those files are overwritten.

**Comment by grafnu** [comment]
Local testing is supported, but the results should be the same. You can do
the same thing, roughly, is that if the local testing is producing
different results than on Travis, you have a point of differentiation. If
local testing is doing the same thing, then we can talk about how that's
not meeting expectations.  As it stands, I still don't understand exactly
what you're trying to do so I can't comment on the nature of the problem.

Also, you don't need to push a PR or anything for travis to run. If you
have it set up, you can simply push your branch and it will run a test.
E.g., see my personal travis setup
<https://travis-ci.org/grafnu/daq/branches>, you can see all my working
branches in various states. If you push your branch up then I can pull it
down and see how it works for me.

However, if you're doing local testing with an exact match of the
integration version, and you're still experiencing problems -- then it's
something different. In that case, including the test output log
(inst/cmdrun.log) goes a long way into clarifying what the problem is.
There's a lot of details in there that show exactly what the system is
doing and where it may be getting stuck -- not something that's easy to
translate into a few english words.

If you're running into a "3 ports available" limit, then unless you're
working with a physical switch, you can arbitrarily increase the number of
ports (up to 20 or so), as shown in the test_many.sh script
<https://github.com/grafnu/daq/blob/master/testing/test_many.sh#L17>.

**Comment by jhughesbiot** [comment]
I attempted to increase the sec_ports to 7 so that all 6 would run in parallel and not lose any of the nodes being tested but the same limitations of the network exists.  Only 3 devices seem to be possible with the test_aux.sh.  I need to have all the device node reports available at the end of the test. It is impossible to review the results to confirm the reasons for test failures for the TLS module specifically since it does not exist for the final 3 faux devices in this test.

**Comment by grafnu** [comment]
The command "sudo testing/test_aux.sh 2>&1 | tee -a test_aux.log" will
capture the log output into a file so I might be able to help you.
test_aux.sh is setup to only run 3 devices, so it's not going to magically
work with some tweaks that's more than just changing that parameter.  It's
not meant to be a general-purpose testing script, it was a specific set of
integration tests.  If you're just trying to test one specific thing, then
you'll be better off setting up your run to test that thing rather than
using test_aux.sh (aka right tool for right job).  In the test_aux/sh case,
the "3" devices comes from the intf_names and startup_cmds settings that
actually invoke the 3 devices, it's not about the number of ports available.

**Comment by jhughesbiot** [comment]
The problem is when working on a new test or updating a test module.  Travis will run this test and will have a new output that needs to match the test_aux.out file.  If you have an issue with that module for a specific device and that device's test logs are destroyed by the end of the test, you have no access to the run logs to help troubleshoot. 

If there's a way to run a specific module against a specific faux device in the same parameters of the test_aux and or test_base configurations, then that's what i'm after.  Essentially this is the same issue as https://github.com/faucetsdn/daq/issues/253 i'm describing.

Right now a change in code to verify, even with just running test_aux is about 25 minutes just to verify it.  If it was a push to travis to check the full build, that's over an hour.  Very hard to troubleshoot and confirm minor code changes in a timely manner with that kind of wait time.

Is it possible to just update the test_aux as well in all areas to support the full devices it is testing?  If it's 6 now, it needs to support 6 ports for the DUT's. If increased, it needs to be updated too?  This seems to make more sense than destroying run logs that are useful for troubleshooting along with the test_aux.log.

**Comment by grafnu** [comment]
I don't understand what the 6 devices are that you keep referring to.
 When you say "if you have an issue with that module for a specific device"
-- can you give an example of what you mean by "specific device"?  I still
don't understand what you're trying to do and therefore what the problem
might be -- so I'm assuming there's some bad assumptions in here somewhere
about what's going on.

If you need to update the testing/test_aux.out file to match any local code
changes, then I typically edit it manually (since most changes should be
mindor), or you can copy it form out/test_aux.out after a local run of
testing/test_aux.sh.

**Comment by grafnu** [comment]
Also, if you had a branch you're working with that exemplifies the
problem that would really help -- having an actual branch with actual code
would go a long way to specifying what you're trying to do because it
removes all ambiguity. It doesn't need to "work" -- but it will at least be
an exact statement of the situation.

**Comment by jhughesbiot** [comment]
The 6 devices i'm referring to are the 6 mac addresses in misc/test_site that are used during the test_aux.sh.  When the tests start, it has 3 ports available, 3 of those devices get put on an available port and the tests are run.  As each port frees up, the next one available gets loaded onto that port, restarting a test and so the run logs for those first 3 are deleted and replaced with the next 3.  Because the testing loads the results into memory to compare against the output file, it doesn't matter to the testing script but for somebody trying to troubleshoot, it's critical to have access to those logs for verification/troubleshooting.

There is no extra code or branch needed at this point to replicate this, it's how the current testing code works.  What i'm saying is that I want to verify what i'm doing is actually giving me the results I expect by looking at the run logs to see if I have any issues but I can't because the TLS module doesn't get used on the second 3 of the test_site mac addresses, only the first 3.

I need to create a new fork from faucetsdn/daq and move my tls updates from the grafnu fork I have but you could review the initial work here https://github.com/jhughesbiot/daq/tree/tls-version-testing until I remove this after a new fork.  I know it's not ready, but that's partially because I'm trying to figure out how to verify things without having access to the final device tests run logs.

**Comment by grafnu** [comment]
Ok, so usually in this situation (developing a specific test), I would
recommend streamlining the process to focus down on what you want, rather
than trying to pull out what you want from everything.

If you only care about results from a particular device, then don't run the
other devices. Not only will it be faster, but it won't clobber the results
with results from other devices.

If you are looking for debugging information from a particular aspect of
something (e.g. output from a specific file), then it's easy to add a log
dump command in the test script so you can see the output.

Also note that test_aux.sh runs the setup twice, which is likely what
you're running into.  Search the file for "cmd/run" and you will see it in
two places. I'm assuming then that it's the second one that's clobbering
the first giving you the problem -- so just comment out the second one.

This almost-PR shows what I mean
<https://github.com/faucetsdn/daq/compare/master...grafnu:testfix?expand=1>.
Also, it only runs the test_aux.sh script, not all of them -- so can make
Travis testing faster if you care about that.

**Comment by jhughesbiot** [comment]
I should be able to remove that extra run from the test script to review results. 

I can see how you removed it from that link and this his probably should be a separate thread at this point but it seems like we should be combining the 6 devices into a single run and comparing results.  A double run command seems like a lot of overhead and increased time to complete the tests and removing it completely makes the testing less valuable as those situations are no longer checked.

**Comment by jhughesbiot** [comment]
> Check if the cipher suite name includes both ECDH and ECDSA with minimum bit length of 224 - WARNING if not.

What is meant by "WARNING?.  Is this just informative with no effect on the results?  Do we care about it if it doesn't actually effect the result?

**Comment by jhughesbiot** [comment]
Need further clarification on the bit length referred to in the cipher suite as it is a different bit length than referred to in the public key.

**Comment by grafnu** [comment]
Jonathan, I don't have an answer to your specific question, but -- the
system right now more-or-less supports { pass, fail, skip } results -- as
you cite there is no "warn" -- but if that feature was useful then it could
be implemented.  I think one possible use case for it would be "this is OK
for now, but is likely to be turned into a fail in the future, so it should
be addressed".

**Comment by jhughesbiot** [comment]
There is kind of this concept of conditional pass warning in the BACnet pics test as it relates to optional. Elements of the test are passed with warning but allow the test to pass if they're optional and not present.  I am basically adopting a similar method.  This will log as pass or warning within the test but not effect the test itself.

I will create a PR in a few with my interpretation of this then and we can decide what changes to make there.  If we decide to make it required later, then it'll be a simple matter of using the results for the cipher as part as the final pass/fail.

**Comment by pisuke** [comment]
Addressed in #626, #551 and #552
