### ISSUE TITLE
testing/test_aux.sh continuous messages

### ISSUE THREAD

**Issue by em-redstone** [faucetsdn/daq#268]
Hi guys,

Would like to ask if anyone is also experiencing this recent behaviour from the testing/test_aux.sh script after it finishes? Is there something which needs to be configured now before running the script?

After finishing, it continues to display these messages. I have tested it on a fresh master repository and on several machines and it still persists.

![cropped](https://user-images.githubusercontent.com/60139604/76759129-fdd18e80-6782-11ea-8abc-61e3519edede.png)

Any advice would be appreciated, many thanks!

**Comment by grafnu** [comment]
This is happening because you're killing the script interactively (^C), and
there's still a background process running that's waiting for activate.log.
The way to fix it is to look through the process table for the process
that's doing this and killing it.  Or,  you can make that file exist and it
should exit naturally:

touch inst/run-port-03/nodes/hold03/activate.log

test_aux.sh wasn't really intended to run on the command line, so there
will be problems like this that crop up. Just recently (Friday) I put in a new
capability for testing individual containers
<https://github.com/faucetsdn/daq/blob/master/docs/module_test.md>, so
depending on what you're doing, that may be sufficient -- PTAL and let me
know.

**Comment by em-redstone** [comment]
Many thanks for the advice Trevor, will have a look.
