### ISSUE TITLE
Validate connection.dhcp_long

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#335]

**Comment by noursaidi** [comment]
@em-redstone I'm validating this test but running into some difficulties. I'm wondering if you haveany documentation or information to advise on the test method & configuration requirements (e.g. DAQ parameters), that would be very helpful.

**Comment by henry54809** [comment]
@noursaidi  You can look at an example config under the dhcp integration test: https://github.com/faucetsdn/daq/blob/b1f704e5b76f9796ed0781ff7a3e012763f1441e/testing/test_dhcp.sh#L31

**Comment by em-redstone** [comment]
Hi @noursaidi, 

These are some of the info I could get from the old DAQ sheet regarding this test:

"This test verifies if the device re-requests a DHCP lease after its lease has expired.

Disconnect device and wait for lease time to expire. Reconnect device and check it requests IP address

Check with tcpdump that a DHCPREQUEST message is sent by the device after the lease has expired."

From what I remember it just looks for an arp packet to see if the device has re-requested a DHCP lease.

Hope this helps.

**Comment by noursaidi** [comment]
Thanks @henry54809 , it looks like that's a recent test into the DAQ framework which appears to fulfill the same purpose as the connection.dhcp_long under the networking module which I was looking at. It also seems more appropriate, as it's integrated into the networking configuration, compared to the latter which rather read-only and relies on monitoring the packet scan. @pisuke thoughts?

Thanks @em-redstone , do you know why it looks for an ARP packet? I would have thought it should have looked for a DHCP request as your text mentioned. 

The test passes, even when there have been no DHCP requests from a device, which doesn't seem to fulfill the test purpose. That's also why I was wondering about any intended configuration, e.g. if scan lengths or DHCP lease periods.

**Comment by pisuke** [comment]
Thanks for looking into this.
The ARP packet should be of the DHCPREQUEST type, so a more specific test should be done.
The test should configure DAQ accordingly as suggested by Haoli.

**Comment by noursaidi** [comment]
@pisuke I agree with you, I've taken a look into how it runs.
When _long_response_ is enabled, the DHCP server will be configured to ignore a client for a preset _long_dhcp_response_sec_ (default 105s, configured in system.conf) period of time. The idea is that the device will not be able to renew DHCP lease, thus it expires and the client must request a new lease.

The parameter _initial_dhcp_lease_time_ (default 120s) determines how long the initial leases is for. Before any tests are run, the DHCP lease time is changed to the _dchp_lease_time_ (default 500s). Therefore, the _long_dchp_response_sec_ needs to be at least almost as long as the initial DHCP lease time in order for the lease to expire.

This is all captured by startup.pcap, example -  https://gist.github.com/noursaidi/0cd24cb9d1a67bffeb5ca53da8d8eba9 ). It seems that there is sufficient information to ascertain what has happened.

@em-redstone what I think then needs to be done is to modify the network/connection.dchp_long test so that it reads the startup.pcap file. It will need to look through this to confirm that a lease has expired and that new lease has subsequently obtained (ACK packet). 

@pisuke @em-redstone However, it seems that the test cannot fail. What I've found is that if the device is unable to obtain a new lease and it has been set to _long_response_ within DAQ, DAQ will time out and no tests are run. So simply by virtue of the network/connection.dchp_long test running, all it has to do is check within module_config if the DHCP mode is _long_response_ and then pass if so otherwise skip.

**Comment by pisuke** [comment]
@noursaidi I'm not sure what is meant by "the test cannot fail".
The aim of the test is to check that the device issues a DHCPREQUEST after having been disconnected and after the DHCP lease has expired.
My questions are:
* has the device been physically disconnected by the test and then reconnected after the lease has expired?
* has the lease expired? is the test checking the output of this interaction from the pcap file?
* has the test a way to ensure that the device is reconnected after the lease time has expired?

**Comment by noursaidi** [comment]
@pisuke apologies I read my previous comment back and it was not too clear, sorry for any confusion.

The test does not currently meet the requirements and does not do what you have stated. I have suggested in my previous comment some changes which could be implemented in order to allow it to do what it needs to do, these rely on using the "long_response" option built into the DAQ framework. To answer your questions directly:

- _has the device been physically disconnected by the test and then reconnected after the lease has expired?_  - No the test does not do this, though I am not sure of any method to physically disconnect the device. I have suggested rather to use the "long_response" option within DAQ to allow the lease to expire (effectively disconnected?)
- _has the lease expired? is the test checking the output of this interaction from the pcap file?_ No,  the test does not do this. One way could be for the test to use the startup.pcap file and look for the loss of the IP address (DHCP discover sent from 0.0.0.0)
- _has the test a way to ensure that the device is reconnected after the lease time has expired?_ - No, the test does not do this. One way could be for the test to use the startup.pcap to look for the ACK packet which confirms a new DHCP lease has been acquired and should therefore be connected. 

My comment regarding "the test cannot fail" is that from my testing and understanding, when using the "long_response" option, the DAQ framework effectively does all of the above, however without any explicit reporting. The device will either successfully send the DHCPREQUEST and obtain a new DHCP lease (a pass); or it will not (a fail). When the device fails and does not do this, DAQ will time out and terminate all test runs, so no tests (e.g. network module, security module) are run, and the test report is effectively blank. Therefore, the "connection.dhcp_long" could avoid reimplementing functionality built into DAQ and only report a pass when "long_response" option is enabled, or a skip when it is not.

I hope this has cleared up what I meant, please let me know or if I have gotten it wrong

**Comment by pisuke** [comment]
Closing this issue as the disconnect_long test has now been removed from the test plan.
