### ISSUE TITLE
NTP Update Test Validity

### ISSUE THREAD

**Issue by jhughesbiot** [faucetsdn/daq#622]
I am not sure the current requirements behind connection.network.ntp_update are actually valid.  Since this test was introduced, it always fails even on known good devices that should be passing this test.  I have concerns that either the implementation and/or the qualification definitions around this test are not adequate in generating pass results.

**Comment by noursaidi** [comment]
@jhughesbiot can you share which devices and packet captures if you have these from devices which are failing the test that you think should pass? How long was the monitor_scan period set to? This needs to be at least a few minutes to allow the device to synchronize with the local NTP server. The other reason the test might fail is if the device does not synchronize with the NTP server provided from DHCP, which some devices may not support.

**Comment by jhughesbiot** [comment]
There is no requirement that the device uses the provided DHCP NTP server in validation.  This is just an optional way of setting the DHCP server and is not actually defined anywhere for failure of this test module.  Either way, I have tested two devices, one that supports DHCP resolving of the NTP server information and the other which has manually configured NTP servers. The manual entry device is an easyio fs-32 which passes this test when validated manually not using the leap indicator as an indication as synchronization but just confirming time synchronization reporting in the device directly.

The startup.pcap file covers all of the requirements except for one (bold), which i'm not sure of it's validity in this process:

The calculated offset is less than 0.128 seconds and the final poll does not have **a leap indicator of 3** (unsynchronized).

This value always shows 3 even after multiple client/server communication packets.  I have had the customer review on their end with SSH access and they can confirm that their device is actually updated to the correct time when pointed at a local NTP server.
 
I haven't modified anything in the default timing of the DAQ tests for scanning but there are plenty of packets within the startup.pcap to handle everything except that leap indicator requirement.  I am only guessing at the failure of the leap indicator based on the test description in the network [readme](https://github.com/faucetsdn/daq/tree/master/subset/network) file and comparing to the .pcap files directly.  I have not dissected the actual implementation to confirm the result failure.  There also does not appear to be any logging around this test for validation either so I don't have a lot to go on to determien the failure other than requirements vs capture file results.

[startup_dhcp.zip](https://github.com/faucetsdn/daq/files/5157662/startup_dhcp.zip)

[startup_manual.zip](https://github.com/faucetsdn/daq/files/5157665/startup_manual.zip)

**Comment by noursaidi** [comment]
For the ntp.update test,  it uses monitor.pcap rather than startup.pcape, so it could be that it became "un-syncronized" later on.

It also checks that a device is synchronized with the local NTP server which DAQ provisions. This is a random IP address, so I'm not sure it's possible to configure it in advance for this test. I think it's accepted as a caveat of the test that if the device doesn't support assigning an NTP server through DHCP then it fails this test.

The leap indicator flag is used to determine if a device is has actually accepted the NTP server as a time source and is synchronizing to it.  Even if a device is polling an NTP server and the offset is tiny (not uncommon if it was already synchronized to the other NTP server just before the test), it might not accept. Depending on configuration, it usually just takes a while and eventually accepts it when its the only server. Recomended that monitor_scan_secs is set to 5 minutes to allow this to happen.

The behavior has been tested on Linux  based devices and so far seems to work as expected. If the device uses NTPD, you can see when the NTP server is being synchronized with using `ntpq -p`, and usually it has leap indicator 3 until it accepts the server. If the device uses Chrony, you can use `chronyc sources`, but with it the leap indicator is rarely 3 unless the time difference is very large, so should pass if the calculated offset is <0.128s.

If you find that its failing on a large number of devices which you think should pass, then maybe the leap indicator require could be removed and it could just check that it polls the local server and the offset is small, but I think its a good additional check if it's working reliably. There was some additional discussion on https://github.com/faucetsdn/daq/pull/525#issuecomment-661413603 and the test definition document

**Comment by jhughesbiot** [comment]
There is no indication that it should be required to use the NTP server created during the DAQ tests, I believe this was added for device that requires being set by DHCP.  There is also no requirement anywhere in device qualification that NTP is required to be set via DHCP so I believe this is an incorrect statement and/or requirement being applied to this test.

From the readme of that test that indicates startup.pcap is also used. 
```

Note for test developers
The functional test code is included in the ntp_tests.py file.

The test reads packets from startup.pcap and monitor.pcap.
```

and 
```

NTP Update
The following criteria are used to determine whether a DUT has synced its clock with the NTP server provided by DAQ:

A minimum of 2 NTP packets are present in startup.pcap and monitor.pcap (one potential poll).
```

On inspection of the monitor.pcap, the leap indicator is 0 for the easy io device but still failing.  For the vergesense device it is still reporting a indicator of 3.

` Recomended that monitor_scan_secs is set to 5 minutes to allow this to happen.`
Can you elaborate on this? Not sure this will change the easyio results but maybe vergesense due to it resolving NTP via DHCP.

**Comment by noursaidi** [comment]
I think the readme needs updating, as the module was updated to use the
monitor.pcap for test 27 and does not seem to be reflected in the
documentation.

RE the local NTP server, I’ll confirm with Francesco if this was a test
description change and a new requirement or it’s been misinterpreted and
needs amending in the test.

The additional time should allow the vergesense device to synchronise, but
wouldn’t impact the easyio device because that one does not seem to be
synchronising with the local server which the test is currently configured
to look for

**Comment by jhughesbiot** [comment]
Is there a configuration in a config file to increase the monitor.pcap time or is this an update to the test code itself?

**Comment by noursaidi** [comment]
In system.yaml you can use the parameter is
monitor_scan_sec
and the value is in seconds. You can refer to the
config/system/default.yaml for an example.
